# Generated by Django 4.2 on 2023-05-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='classbatches',
            field=models.ManyToManyField(to='rosters.classbatch'),
        ),
        migrations.AddField(
            model_name='learner',
            name='secret_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='classbatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_classbatch', to='rosters.classbatch'),
        ),
    ]
