# Generated by Django 4.2 on 2023-05-30 14:36

from django.db import migrations

def forward(apps, schema_editor):
    Learner = apps.get_model("rosters", "Learner")
    for learner in Learner.objects.all():
        learner.classbatches.add(learner.classbatch)

class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0002_learner_classbatches_learner_secret_id_and_more'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
