# Generated by Django 4.2 on 2023-05-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0003_auto_20230530_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='classbatch',
        ),
    ]
