# Generated by Django 4.2 on 2023-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0004_remove_learner_classbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='classbatches',
            field=models.ManyToManyField(related_name='learners', to='rosters.classbatch'),
        ),
    ]
